 const a = [1]
 

try{
  const b = a[0]/0
    
}catch(err){
     console.error(err)
}

console.log("Hola paso el try")